// <auto-generated />
using Dwapi.SettingsManagement.Infrastructure;
using Dwapi.SharedKernel.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Dwapi.SettingsManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SettingsContext))]
    [Migration("20180207121325_Settings2018FEB07001")]
    partial class Settings2018FEB07001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.DatabaseProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(100);

                    b.Property<int>("DatabaseType");

                    b.Property<Guid>("EmrSystemId");

                    b.Property<string>("Host")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.Property<int?>("Port");

                    b.Property<string>("Username")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EmrSystemId");

                    b.ToTable("DatabaseProtocols");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.EmrSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("Version")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("EmrSystems");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.RestProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken")
                        .HasMaxLength(100);

                    b.Property<Guid>("EmrSystemId");

                    b.Property<string>("Url")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EmrSystemId");

                    b.ToTable("RestProtocols");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.DatabaseProtocol", b =>
                {
                    b.HasOne("Dwapi.SettingsManagement.Core.Model.EmrSystem")
                        .WithMany("DatabaseProtocols")
                        .HasForeignKey("EmrSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.RestProtocol", b =>
                {
                    b.HasOne("Dwapi.SettingsManagement.Core.Model.EmrSystem")
                        .WithMany("RestProtocols")
                        .HasForeignKey("EmrSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
