// <auto-generated />
using Dwapi.SettingsManagement.Infrastructure;
using Dwapi.SharedKernel.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Dwapi.SettingsManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SettingsContext))]
    partial class SettingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.CentralRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("SubscriberId")
                        .HasMaxLength(50);

                    b.Property<string>("Url")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CentralRegistries");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.DatabaseProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdvancedProperties")
                        .HasMaxLength(100);

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(100);

                    b.Property<int>("DatabaseType");

                    b.Property<Guid>("EmrSystemId");

                    b.Property<string>("Host")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .HasMaxLength(100);

                    b.Property<int?>("Port");

                    b.Property<string>("Username")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EmrSystemId");

                    b.ToTable("DatabaseProtocols");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.Docket", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Dockets");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.EmrSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("IsMiddleware");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("Version")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("EmrSystems");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.Extract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Destination");

                    b.Property<string>("Display")
                        .HasMaxLength(100);

                    b.Property<string>("DocketId");

                    b.Property<Guid>("EmrSystemId");

                    b.Property<string>("ExtractSql")
                        .HasMaxLength(8000);

                    b.Property<bool>("IsPriority");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<decimal>("Rank");

                    b.HasKey("Id");

                    b.HasIndex("DocketId");

                    b.HasIndex("EmrSystemId");

                    b.ToTable("Extracts");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.RestProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken")
                        .HasMaxLength(100);

                    b.Property<Guid>("EmrSystemId");

                    b.Property<string>("Url")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EmrSystemId");

                    b.ToTable("RestProtocols");
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.DatabaseProtocol", b =>
                {
                    b.HasOne("Dwapi.SettingsManagement.Core.Model.EmrSystem")
                        .WithMany("DatabaseProtocols")
                        .HasForeignKey("EmrSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.Extract", b =>
                {
                    b.HasOne("Dwapi.SettingsManagement.Core.Model.Docket")
                        .WithMany("Extracts")
                        .HasForeignKey("DocketId");

                    b.HasOne("Dwapi.SettingsManagement.Core.Model.EmrSystem")
                        .WithMany("Extracts")
                        .HasForeignKey("EmrSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dwapi.SettingsManagement.Core.Model.RestProtocol", b =>
                {
                    b.HasOne("Dwapi.SettingsManagement.Core.Model.EmrSystem")
                        .WithMany("RestProtocols")
                        .HasForeignKey("EmrSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
