CREATE TABLE patientextract(
	 PatientPK int NOT NULL,
	 SiteCode int NOT NULL,
	 Emr nvarchar(150) NULL,
	 Project nvarchar (150) NULL,
	 Processed bit NULL,
	 FacilityName nvarchar(150) NULL,
	 Gender nvarchar(150) NULL,
	 DOB datetime NULL,
	 RegistrationDate datetime NULL,
	 RegistrationAtCCC  datetime  NULL,
	 RegistrationATPMTCT   datetime  NULL,
	 RegistrationAtTBClinic   datetime  NULL,
	 PatientSource   nvarchar (150) NULL,
	 Region   nvarchar (150) NULL,
	 District   nvarchar (150) NULL,
	 Village   nvarchar (150) NULL,
	 ContactRelation   nvarchar (150) NULL,
	 LastVisit   datetime  NULL,
	 MaritalStatus   nvarchar (150) NULL,
	 EducationLevel   nvarchar (150) NULL,
	 DateConfirmedHIVPositive   datetime  NULL,
	 PreviousARTExposure   nvarchar (150) NULL,
	 PreviousARTStartDate   datetime  NULL,
	 StatusAtCCC   nvarchar (150) NULL,
	 StatusAtPMTCT   nvarchar (150) NULL,
	 StatusAtTBClinic   nvarchar (150) NULL,
	 Id char(38)  NOT NULL,
	 PatientID   nvarchar (150) NULL,
	 QueueId   nvarchar (150) NULL,
	 Status   nvarchar (150) NULL,
	 StatusDate   datetime  NULL,
    
    primary key (PatientPK, SiteCode)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
