CREATE TABLE  patientbaselinesextract (
	 Emr   nvarchar (150) NULL,
	 Project   nvarchar (150) NULL,
	 Processed   bit  NULL,
	 Id   char(38)  NOT NULL,
	 bCD4   int  NULL,
	 bCD4Date   datetime  NULL,
	 bWAB   int  NULL,
	 bWABDate   datetime  NULL,
	 bWHO   int  NULL,
	 bWHODate   datetime  NULL,
	 eWAB   int  NULL,
	 eWABDate   datetime  NULL,
	 eCD4   int  NULL,
	 eCD4Date   datetime  NULL,
	 eWHO   int  NULL,
	 eWHODate   datetime  NULL,
	 lastWHO   int  NULL,
	 lastWHODate   datetime  NULL,
	 lastCD4   int  NULL,
	 lastCD4Date   datetime  NULL,
	 lastWAB   int  NULL,
	 lastWABDate   datetime  NULL,
	 m12CD4   int  NULL,
	 m12CD4Date   datetime  NULL,
	 m6CD4   int  NULL,
	 m6CD4Date   datetime  NULL,
	 PatientPK   int  NOT NULL,
	 PatientID   nvarchar (150) NULL,
	 SiteCode   int  NOT NULL,
	 QueueId   nvarchar (150) NULL,
	 Status   nvarchar (150) NULL,
	 StatusDate   datetime  NULL,
    
    primary key (Id),
    
    constraint FK_PatientBaselineExtract_PatientExtract_PatientPK_SiteCode foreign key (PatientPK, SiteCode)
    references patientextract(PatientPK, SiteCode)
    ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;