CREATE TABLE  patientvisitextract (
	 Emr   nvarchar (150) NULL,
	 Project   nvarchar (150) NULL,
	 Processed   bit  NULL,
	 Id   char(38)  NOT NULL,
	 VisitId   int  NULL,
	 VisitDate   datetime  NULL,
	 Service   nvarchar (150) NULL,
	 VisitType   nvarchar (150) NULL,
	 WHOStage   int  NULL,
	 WABStage   nvarchar (150) NULL,
	 Pregnant   nvarchar (150) NULL,
	 LMP   datetime  NULL,
	 EDD   datetime  NULL,
	 Height   decimal (18, 2) NULL,
	 Weight   decimal (18, 2) NULL,
	 BP   nvarchar (150) NULL,
	 OI   nvarchar (150) NULL,
	 OIDate   datetime  NULL,
	 SubstitutionFirstlineRegimenDate   datetime  NULL,
	 SubstitutionFirstlineRegimenReason   nvarchar (150) NULL,
	 SubstitutionSecondlineRegimenDate   datetime  NULL,
	 SubstitutionSecondlineRegimenReason   nvarchar (150) NULL,
	 SecondlineRegimenChangeDate   datetime  NULL,
	 SecondlineRegimenChangeReason   nvarchar (150) NULL,
	 Adherence   nvarchar (150) NULL,
	 AdherenceCategory   nvarchar (150) NULL,
	 FamilyPlanningMethod   nvarchar (150) NULL,
	 PwP   nvarchar (150) NULL,
	 GestationAge   decimal (18, 2) NULL,
	 NextAppointmentDate   datetime  NULL,
	 PatientPK   int  NOT NULL,
	 PatientID   nvarchar (150) NULL,
	 SiteCode   int  NOT NULL,
	 QueueId   nvarchar (150) NULL,
	 `Status`   nvarchar (150) NULL,
	 StatusDate   datetime  NULL,
    
    primary key (Id),
    
    constraint FK_PatientVisitExtract_PatientExtract_PatientPK_SiteCode foreign key (PatientPK, SiteCode)
    references patientextract(PatientPK, SiteCode)
    ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;