CREATE TABLE temppatientextract(
	Id int(11) NOT NULL auto_increment,
	FacilityName nvarchar(150) NULL,
	SatelliteName nvarchar(150) NULL,
	Gender nvarchar(150) NULL,
	DOB datetime NULL,
	RegistrationDate datetime NULL,
	RegistrationAtCCC datetime NULL,
	RegistrationATPMTCT datetime NULL,
	RegistrationAtTBClinic datetime NULL,
	Region nvarchar(150) NULL,
	PatientSource nvarchar(150) NULL,
	District nvarchar(150) NULL,
	Village nvarchar(150) NULL,
	ContactRelation nvarchar(150) NULL,
	LastVisit datetime NULL,
	MaritalStatus nvarchar(150) NULL,
	EducationLevel nvarchar(150) NULL,
	DateConfirmedHIVPositive datetime NULL,
	PreviousARTExposure nvarchar(150) NULL,
	PreviousARTStartDate datetime NULL,
	StatusAtCCC nvarchar(150) NULL,
	StatusAtPMTCT nvarchar(150) NULL,
	StatusAtTBClinic nvarchar(150) NULL,
	Emr nvarchar(150) NULL,
	Project nvarchar(150) NULL,
	PatientPK int NULL,
	PatientID nvarchar(150) NULL,
	FacilityId int NULL,
	SiteCode int NULL,
	DateExtracted datetime NOT NULL,
	CheckError bit NOT NULL,
    
    primary key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;