CREATE TABLE temppatientartextract(
	Id int(11) NOT NULL auto_increment,
	FacilityName nvarchar(150) NULL,
	Emr nvarchar(150) NULL,
	Project nvarchar(150) NULL,
	DOB datetime NULL,
	AgeEnrollment decimal(18, 2) NULL,
	AgeARTStart decimal(18, 2) NULL,
	AgeLastVisit decimal(18, 2) NULL,
	RegistrationDate datetime NULL,
	PatientSource nvarchar(150) NULL,
	Gender nvarchar(150) NULL,
	StartARTDate datetime NULL,
	PreviousARTStartDate datetime NULL,
	PreviousARTRegimen nvarchar(150) NULL,
	StartARTAtThisFacility datetime NULL,
	StartRegimen nvarchar(150) NULL,
	StartRegimenLine nvarchar(150) NULL,
	LastARTDate datetime NULL,
	LastRegimen nvarchar(150) NULL,
	LastRegimenLine nvarchar(150) NULL,
	Duration decimal(18, 2) NULL,
	ExpectedReturn datetime NULL,
	Provider nvarchar(150) NULL,
	LastVisit datetime NULL,
	ExitReason nvarchar(150) NULL,
	ExitDate datetime NULL,
	PatientPK int NULL,
	PatientID nvarchar(150) NULL,
	FacilityId int NULL,
	SiteCode int NULL,
	DateExtracted datetime NOT NULL,
	CheckError bit NOT NULL,
    
    primary key(Id)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
