CREATE TABLE temppatientbaselinesextract(
	Id int(11) NOT NULL auto_increment,
	bCD4 int NULL,
	bCD4Date datetime NULL,
	bWAB int NULL,
	bWABDate datetime NULL,
	bWHO int NULL,
	bWHODate datetime NULL,
	eWAB int NULL,
	eWABDate datetime NULL,
	eCD4 int NULL,
	eCD4Date datetime NULL,
	eWHO int NULL,
	eWHODate datetime NULL,
	lastWHO int NULL,
	lastWHODate datetime NULL,
	lastCD4 int NULL,
	lastCD4Date datetime NULL,
	lastWAB int NULL,
	lastWABDate datetime NULL,
	m12CD4 int NULL,
	m12CD4Date datetime NULL,
	m6CD4 int NULL,
	m6CD4Date datetime NULL,
	Emr nvarchar(150) NULL,
	Project nvarchar(150) NULL,
	PatientPK int NULL,
	PatientID nvarchar(150) NULL,
	FacilityId int NULL,
	SiteCode int NULL,
	DateExtracted datetime NOT NULL,
	CheckError bit NOT NULL,
    
    primary key (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;