CREATE TABLE temppatientvisitextract(
	Id int(11) NOT NULL auto_increment,
	FacilityName nvarchar(150) NULL,
	Emr nvarchar(150) NULL,
	Project nvarchar(150) NULL,
	VisitId int NULL,
	VisitDate datetime NULL,
	Service nvarchar(150) NULL,
	VisitType nvarchar(150) NULL,
	WHOStage int NULL,
	WABStage nvarchar(150) NULL,
	Pregnant nvarchar(150) NULL,
	LMP datetime NULL,
	EDD datetime NULL,
	Height decimal(18, 2) NULL,
	Weight decimal(18, 2) NULL,
	BP nvarchar(150) NULL,
	OI nvarchar(150) NULL,
	OIDate datetime NULL,
	Adherence nvarchar(150) NULL,
	AdherenceCategory nvarchar(150) NULL,
	SubstitutionFirstlineRegimenDate datetime NULL,
	SubstitutionFirstlineRegimenReason nvarchar(150) NULL,
	SubstitutionSecondlineRegimenDate datetime NULL,
	SubstitutionSecondlineRegimenReason nvarchar(150) NULL,
	SecondlineRegimenChangeDate datetime NULL,
	SecondlineRegimenChangeReason nvarchar(150) NULL,
	FamilyPlanningMethod nvarchar(150) NULL,
	PwP nvarchar(150) NULL,
	GestationAge decimal(18, 2) NULL,
	NextAppointmentDate datetime NULL,
	PatientPK int NULL,
	PatientID nvarchar(150) NULL,
	FacilityId int NULL,
	SiteCode int NULL,
	DateExtracted datetime NOT NULL,
	CheckError bit NOT NULL,
    
    primary key(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;