name: deploy to qa
on:
  push:
    branches: [ dev ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/github-workflows/
          sudo rm -rf dwapi
          sudo mkdir dwapi
          sudo chown -R cicd2:cicd2 dwapi
          git config --global --add safe.directory /apps/github-workflows/dwapi 
          git clone -b dev https://user:${{secrets.TOKEN}}@github.com//palladiumkenya/dwapi.git
          cd /apps/github-workflows/dwapi
          git status         
          sudo docker-compose down
          sudo docker-compose rm -f
          sudo docker-compose up --build -d 
          sudo docker push kenyahmis/dwapi:qa
