name: Build and Push Docker Dwapi Image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: 'kenyahmis/dwapi'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '2.1.x'  # Use the appropriate version for your project

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
          node-version: '14.17.6'
          
    - name: Install dependencies
      run: npm install
      working-directory: src/Dwapi
      
    - name: Build the ASP.NET app
      run: dotnet build src/Dwapi/Dwapi.csproj --configuration Release
      
    - name: Build the angular UI
      run: npm run build
      working-directory: src/Dwapi

    - name: Build the project
      run: dotnet publish src/Dwapi/Dwapi.csproj -c Release -o ./publish

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t dwapi:latest . 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the Docker image
        run:  echo "passed"
  push_to_registry:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
